spring:
  config:
    import:
      - application-secret.yaml
      - application-jwt.yaml

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create